project:
  type: website

website:
  title: "Solène Berney"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DSF_quarto_publish.qmd
        text: ML Forecasting
      - href: Strava_quarto_publish.qmd
        text: Strava API
      - href: Hackathon.qmd
        text: Hackathon
        
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/solene-berney-unisg/
        aria-label: LinkedIn
      - icon: envelope
        href: "mailto:solenebny@gmail.com"
        aria-label: Email
  
  page-footer:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/solene-berney-unisg/


format:
  html:
    page-layout: article
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

